# Generated by Django 3.1 on 2021-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.FileField(default='static/user.png', upload_to=''),
        ),
    ]
