# Generated by Django 3.1 on 2021-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211001_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='profile/user.png', upload_to='profile'),
        ),
    ]
