# Generated by Django 3.1 on 2021-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211025_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.URLField(blank=True, default='https://img-static-s3.s3.us-west-2.amazonaws.com/rough/aaron-burden-y02jEX_B0O0-unsplash.jpg', null=True),
        ),
    ]
