# Generated by Django 3.1 on 2021-12-04 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20211104_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curate',
            field=models.ManyToManyField(blank=True, related_name='curate', to=settings.AUTH_USER_MODEL),
        ),
    ]
